### ISSUE TITLE
TimeoutError: Timeout awaiting 'request' for 30000ms

### ISSUE THREAD

**Issue by phbo85** [gatsbyjs/gatsby-source-wordpress-experimental#220]
Just installed everything from the starter, wordpress is running the plugins and getting pages, posts and so on works. However, the script encounters and error when fetching MediaItems.

```
$ npm run develop

> using-gatsby-source-wordpress-experimental@0.0.1 develop C:\projects2\gatsby-project-exp
> gatsby develop

success open and validate gatsby-configs - 0.039s
success load plugins - 1.514s

 ERROR 

(node:2504) ExperimentalWarning: The dns.promises API is experimental

success onPreInit - 0.052s
success initialize cache - 0.026s
success copy gatsby files - 0.080s
success onPreBootstrap - 0.019s
⠀
info  gatsby-source-wordpress 

        This is either your first build or the cache was cleared.
        Please wait while your WordPress data is synced to your Gatsby cache.

        Maybe now's a good time to get up and stretch? :D

success  gatsby-source-wordpress  writing GraphQL queries to disk at ./WordPress/GraphQL/ - 0.258s
success  gatsby-source-wordpress  ingest WPGraphQL schema - 1.158s
success createSchemaCustomization - 1.618s
success  gatsby-source-wordpress  fetch root fields - 0.582s
success  gatsby-source-wordpress  Comment - 0.647s - fetched 0
success  gatsby-source-wordpress  Menu - 0.712s - fetched 2
success  gatsby-source-wordpress  Category - 0.806s - fetched 5
success  gatsby-source-wordpress  ContentType - 0.810s - fetched 3
success  gatsby-source-wordpress  MenuItem - 0.896s - fetched 36
success  gatsby-source-wordpress  PostFormat - 0.993s - fetched 0
success  gatsby-source-wordpress  Post - 1.003s - fetched 0
success  gatsby-source-wordpress  Tag - 1.006s - fetched 1
success  gatsby-source-wordpress  Taxonomy - 1.027s - fetched 3
success  gatsby-source-wordpress  UserRole - 1.020s - fetched 0
success  gatsby-source-wordpress  User - 1.019s - fetched 2
success  gatsby-source-wordpress  Page - 3.227s - fetched 34

 ERROR 

(node:2504) ExperimentalWarning: Readable[Symbol.asyncIterator] is an experimental feature. This feature could change at any time

warn Received the below error when trying to fetch
http://www.nottherealdomain.com/wp-content/uploads/2018/06/51AdY5oO2-L-1.jpg
from Page #1386 "Page name test"

https://www.nottherealdomain.com/wp-admin/post.php?post=1386&action=edit



 ERROR 

 gatsby-source-wordpress  failed to process http://wwwnottherealdomain.com/wp-content/uploads/2018/06/51AdY5oO2-L-1.jpg
TimeoutError: Timeout awaiting 'request' for 30000ms

not finished source and transform nodes - 34.401s
not finished  gatsby-source-wordpress  fetching nodes - 34.336s - 105 total
not finished  gatsby-source-wordpress  creating nodes - 31.027s
not finished  gatsby-source-wordpress  MediaItem - 31.029s - fetched 19
not finished Downloading remote files - 30.521s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! using-gatsby-source-wordpress-experimental@0.0.1 develop: `gatsby develop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the using-gatsby-source-wordpress-experimental@0.0.1 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pboch\AppData\Roaming\npm-cache\_logs\2020-10-11T12_13_28_209Z-debug.log
```
Logfile:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\pboch\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'develop' ]
2 info using npm@6.5.0
3 info using node@v10.15.0
4 verbose run-script [ 'predevelop', 'develop', 'postdevelop' ]
5 info lifecycle using-gatsby-source-wordpress-experimental@0.0.1~predevelop: using-gatsby-source-wordpress-experimental@0.0.1
6 info lifecycle using-gatsby-source-wordpress-experimental@0.0.1~develop: using-gatsby-source-wordpress-experimental@0.0.1
7 verbose lifecycle using-gatsby-source-wordpress-experimental@0.0.1~develop: unsafe-perm in lifecycle true
8 verbose lifecycle using-gatsby-source-wordpress-experimental@0.0.1~develop: PATH: C:\Users\pboch\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\projects2\gatsby-project-exp\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\pboch\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\pboch\bin;C:\Python37\Scripts;C:\Python37;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Calibre2;C:\Program Files (x86)\QuickTime\QTSystem;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\wamp64\bin\php\php5.6.16;C:\Program Files (x86)\Skype\Phone;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Microsoft VS Code\bin;C:\Users\pboch\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\Yarn\bin;C:\Users\pboch\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\nodejs;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\pboch\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Git\usr\bin;C:\Users\pboch\AppData\Roaming\Dashlane\5.11.0.19021\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components;C:\Users\pboch\AppData\Roaming\Dashlane\5.11.0.19021\ucrt;C:\Users\pboch\AppData\Local\Microsoft\WindowsApps;C:\Users\pboch\AppData\Local\Yarn\bin;C:\Users\pboch\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\pboch\AppData\Roaming\npm;C:\Users\pboch\AppData\Roaming\Dashlane\6.1907.0.17833\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components;C:\Users\pboch\AppData\Roaming\Dashlane\6.1907.0.17833\ucrt;C:\Users\pboch\AppData\Roaming\Dashlane\6.1907.0.17833\bin\Qt;C:\Users\pboch\AppData\Roaming\Dashlane\6.1907.0.17833\bin\Ssl;C:\Users\pboch\AppData\Local\GitHubDesktop\bin
9 verbose lifecycle using-gatsby-source-wordpress-experimental@0.0.1~develop: CWD: C:\projects2\gatsby-project-exp
10 silly lifecycle using-gatsby-source-wordpress-experimental@0.0.1~develop: Args: [ '/d /s /c', 'gatsby develop' ]
11 silly lifecycle using-gatsby-source-wordpress-experimental@0.0.1~develop: Returned: code: 1  signal: null
12 info lifecycle using-gatsby-source-wordpress-experimental@0.0.1~develop: Failed to exec develop script
13 verbose stack Error: using-gatsby-source-wordpress-experimental@0.0.1 develop: `gatsby develop`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\pboch\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\pboch\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid using-gatsby-source-wordpress-experimental@0.0.1
15 verbose cwd C:\projects2\gatsby-project-exp
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\pboch\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "develop"
18 verbose node v10.15.0
19 verbose npm  v6.5.0
20 error code ELIFECYCLE
21 error errno 1
22 error using-gatsby-source-wordpress-experimental@0.0.1 develop: `gatsby develop`
22 error Exit status 1
23 error Failed at the using-gatsby-source-wordpress-experimental@0.0.1 develop script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by acao** [comment]
possibly an issue with requesting the images? for example, it may be that if you’re using a CDN, it may have triggered some kind of bot detection mechanism. a request timeout on the wordpress could have many sources, and there are of course many factors

**Comment by phbo85** [comment]
Hi @acao! Thank you for your help. I'm not using a CDN and so far I didn't run into any similar issues with v3 of the plugin. I also checked and the image can be accessed manually.

**Comment by uzomao** [comment]
Hey @phbo85 any luck so far?

**Comment by phbo85** [comment]
Hi @uzomao, today I tried upgrading my packages and node to the latest versions, but it's still stuck at the same point. I removed the image that can't be loaded and the reference from the WP post, but then it's stuck on another image. I'm out of ideas.

If anybody wants to try it with my WP installation, I can give you the URL in private.

**Comment by acao** [comment]
because this error is coming from your wordpress installation, its very difficult to track down. is it self hosted? wp engine? apache or nginx?

**Comment by phbo85** [comment]
Hi @acao, the installation is self-hosted... here is some more info, I hope it's helping. If you want to I can send you a mail with the domain.


Server OS : Linux / 64Bit OS
Server Software : Apache
Memcached Enabled : No
Database Software : (Ubuntu)
Database Version : 5.7.28
Maximum No. of Connections : 500
Maximum Packet Size : 64 MB
Database Disk Usage : 24 MB
Index Disk Usage : 6 MB
Check More Database Info
PHP Version : 7.4.10
PHP Max Upload Size : 200 MB
PHP Max Post Size : 200 MB
PHP Max Execution Time : 30 sec
PHP Short Tag : On
PHP Memory Limit : 256 MB

**Comment by acao** [comment]
maybe try increasing max execution time to 90 seconds? looks like the
timeout error your getting is exactly 30 seconds

**Comment by phbo85** [comment]
I tried setting it to 90 seconds, but still getting the same error.

**Comment by phbo85** [comment]
I've updated to the latest version today, also updated node and npm. The problem is solved for me.
