### ISSUE TITLE
ACF Relationship Field throws an error in Gatsby, but not the remote

### ISSUE THREAD

**Issue by gustavpursche** [gatsbyjs/gatsby-source-wordpress-experimental#311]
I'm running into a problem, where a query throws an error, which works on the remote GraphiQL endpoint, when using an ACF Relationship field.

```
query {
  page(id: "730", idType: DATABASE_ID) {
    acf {
      content {
        ... on Page_Acf_Content_FeaturedNews {
          news {
            ... on NewsEntry {
              id
            }
          }
        }
      }
    }
  }
}
```

returns on the remote GraphiQL:

```
{
  "data": {
    "page": {
      "acf": {
        "content": [
          {
            "news": [
              {
                "id": "cG9zdDoyNjI4"
              },
              {
                "id": "cG9zdDoyNjMy"
              },
              {
                "id": "cG9zdDoyNjE3"
              }
            ]
          },
          {}
        ]
      }
    }
  },
  "extensions": {
    "debug": [
      {
        "type": "DEBUG_LOGS_INACTIVE",
        "message": "GraphQL Debug logging is not active. To see debug logs, GRAPHQL_DEBUG must be enabled."
      }
    ]
  }
}
```

but throws an error in Gatsby:

```
{
  "errors": [
    {
      "message": "Cannot read property 'id' of null",
      "locations": [
        {
          "line": 9,
          "column": 13
        }
      ],
      "path": [
        "allWpPage",
        "nodes",
        0,
        "acf",
        "content",
        5,
        "news"
      ],
      "stack": [
        "TypeError: Cannot read property 'id' of null",
        "    at reduce (/home/gustav/Development/coaltransitions/node_modules/gatsby-source-wordpress-experimental/src/steps/create-schema-customization/transform-fields/transform-union.js:49:27)",
        "    at Array.reduce (<anonymous>)",
        "    at resolver (/home/gustav/Development/coaltransitions/node_modules/gatsby-source-wordpress-experimental/src/steps/create-schema-customization/transform-fields/transform-union.js:46:28)",
        "    at wrappedTracingResolver (/home/gustav/Development/coaltransitions/node_modules/gatsby/src/schema/resolvers.ts:518:14)",
        "    at resolveFieldValueOrError (/home/gustav/Development/coaltransitions/node_modules/graphql/execution/execute.js:467:18)",
        "    at resolveField (/home/gustav/Development/coaltransitions/node_modules/graphql/execution/execute.js:434:16)",
        "    at executeFields (/home/gustav/Development/coaltransitions/node_modules/graphql/execution/execute.js:275:18)",
        "    at collectAndExecuteSubfields (/home/gustav/Development/coaltransitions/node_modules/graphql/execution/execute.js:713:10)",
        "    at completeObjectValue (/home/gustav/Development/coaltransitions/node_modules/graphql/execution/execute.js:703:10)",
        "    at completeAbstractValue (/home/gustav/Development/coaltransitions/node_modules/graphql/execution/execute.js:660:10)",
        "    at completeValue (/home/gustav/Development/coaltransitions/node_modules/graphql/execution/execute.js:585:12)",
        "    at completeValueCatchingError (/home/gustav/Development/coaltransitions/node_modules/graphql/execution/execute.js:495:19)",
        "    at /home/gustav/Development/coaltransitions/node_modules/graphql/execution/execute.js:618:25",
        "    at Array.forEach (<anonymous>)",
        "    at forEach (/home/gustav/Development/coaltransitions/node_modules/iterall/index.js:83:25)",
        "    at completeListValue (/home/gustav/Development/coaltransitions/node_modules/graphql/execution/execute.js:614:24)",
        "    at completeValue (/home/gustav/Development/coaltransitions/node_modules/graphql/execution/execute.js:573:12)",
        "    at /home/gustav/Development/coaltransitions/node_modules/graphql/execution/execute.js:492:16",
        "    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
        "    at async Promise.all (index 0)",
        "    at async Promise.all (index 2)",
        "    at async Promise.all (index 0)",
        "    at async Promise.all (index 0)",
        "    at async Promise.all (index 0)"
      ]
    }
  ],
  "data": {
    "allWpPage": {
      "nodes": [
        {
          "acf": {
            "content": [
              {
                "news": null
              },
              {}
            ]
          }
        }
      ]
    }
  },
  "extensions": {}
}
```

**Comment by MitchEff** [comment]
I ran into this and could not fix it no matter what I tried. Deleting the ACF field and making it again worked for me eventually.

**Comment by TylerBarnes** [comment]
@gustavpursche can you share a reproduction /graphql url? This will be a quick/simple fix if I can reproduce it. Thanks!

**Comment by gustavpursche** [comment]
@TylerBarnes thanks for the quick reply! I'll send you an email now with the URL and Basic Auth credentials.

**Comment by holliepearson** [comment]
Did anything further ever happen with this? I'm having the same issue with a flexible content field

**Comment by AlexMorrisonDev716** [comment]
@holliepearson Same here. If you found anything out, please let me know :)

**Comment by AlexMorrisonDev716** [comment]
@holliepearson Try saving the page/post in question again. I was able to resolve this that way. It looks like wp-graphql-acf has an issue with post revisions.
