### ISSUE TITLE
Media download issues

### ISSUE THREAD

**Issue by adrianhewitt** [gatsbyjs/gatsby-source-wordpress-experimental#447]
Been wrestling with this for a few weeks, but I can't seem to get this budging. Whenever i try to build / develop from my cleaned project, i always get hit by this error for many (not all) of the image files:

```
gatsby-source-wordpress  Fetching https://cms.me.com/wp-content/uploads/20
19/09/image.png is taking a long time time (longer
than 15 seconds). This file is 6.85 MB
```

```
RequestError: Timeout awaiting 'request' for 30000ms
    at ClientRequest.<anonymous>
(/Users/me/Repositories/me.com/node_modules/gatsby-source-wordpre
ss-experimental/node_modules/got/dist/source/core/index.js:953:65)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/Users/me/Repositories/me.com/n
ode_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at Timeout.timeoutHandler [as _onTimeout]
(/Users/me/Repositories/me.com/node_modules/gatsby-source-wordpre
ss-experimental/node_modules/got/dist/source/core/utils/timed-out.js:36:25)
    at listOnTimeout (internal/timers.js:556:17)
    at processTimers (internal/timers.js:497:7) {
  name: 'TimeoutError',
  code: 'ETIMEDOUT',
  timings: {
    start: 1612140972803,
    socket: 1612140972803,
    lookup: 1612140972804,
    connect: 1612140972886,
    secureConnect: 1612140973028,
    upload: 1612140973028,
    response: 1612140973105,
    end: undefined,
    error: 1612141002803,
    abort: 1612141002803,
    phases: {
      wait: 0,
      dns: 1,
      tcp: 82,
      tls: 142,
      request: 0,
      firstByte: 77,
      download: undefined,
      total: 30000
    }
  },
  event: 'request'
}
```

i've tried killing the request concurrency using:

```
    {
      resolve: `gatsby-source-wordpress-experimental`,
      options: {
        url: `https://cms.project.com/graphql`,
        schema: {
          requestConcurrency: 1
        },
      }
    },
```

but i'm not even sure the plugin is even listening to that config as it's flying through trying to download the images. that said, the wordpress instance is running on a super fast VPS and shouldn't have any issues with the transfer. Additionally, this wordpress instance was working perfectly with a previous gatsbyjs build... so i'm out of ideas. libraries are all updated etc.

**Comment by TylerBarnes** [comment]
Hi @adrianhewitt the request concurrency you're setting is for GraphQL requests but the warning in your terminal is related to file requests. You want to use this setting instead https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/plugin-options.md#typemediaitemlocalfilerequestconcurrency

**Comment by adrianhewitt** [comment]
assuming you're talking about the local file request concurrency:

```
    {
      resolve: `gatsby-source-wordpress-experimental`,
      options: {
        url: `https://cms.me.com/graphql`,
        schema: {
          requestConcurrency: 1
        },
        type: {
          MediaItem: {
            localFile: {
              requestConcurrency: 1,
            },
          },
        },
      }
    },
```

i cleaned the project and tried to compile it again and it does the same thing, still spits out a whole heap of warnings then timeout errors

**Comment by TylerBarnes** [comment]
@adrianhewitt can you share a reproduction of the problem? That'll help us figure out what's going on. Thanks!

**Comment by CloudBop** [comment]
Sorry to jump in with possibly irrelevant info... I had the same error upgrading today, although it came about from different circumstances. I was using Local and there were https/http clashes and self signed certificates and what not. Not enough to impact on the build until I added a post with an image in Gutenberg, then I started getting the error described as below. It was a 300kb image. Basically kept going until it errored. 

```
gatsby-source-wordpress  Fetching https://cms.me.com/wp-content/uploads/20
19/09/image.png is taking a long time time (longer
than 15 seconds). This file is 6.85 MB
```

Fortunately my issue was resolved by reinstalling my WP into Local and making sure http info were all correct (in WP and Gatsby-config). I haven't needed to reinstall my Gatsby project.

If your site works locally it might be worth trying to flush the permalinks on the live one.

This plugin will allow you to have a better idea regarding what's going on at the WP database level inside the admin of your media area. https://en-gb.wordpress.org/plugins/media-library-assistant/ I used to use that for the old WP-src plugin. It may help you diagnose why some images seem to work and others don't.

Also I found this which may or may not be of interest. https://www.polynique.com/2021/01/26/fix-gatsby-crash-when-uploading-an-image-in-wordpress/

How did you copy the CMS to local? If it works locally, you could try using this plugin https://en-gb.wordpress.org/plugins/all-in-one-wp-migration/ to re-upload your local site.

Again, apologies if totally unhelpful.

**Comment by adrianhewitt** [comment]
For a moment I thought @CloudBop was on the right track (flushing permalinks didn't work, but i then thought about removing auto https redirect on my hosting which seemed to work), but i think my success was mostly due to tethering to my phone in a cafe and having higher burst bandwidth... now back in the office every pathy thing i try doesn't seem to make a difference. (and now at home with a faster internet connection i get the warnings but none of the timeouts)

also worth noting that with 

```
localFile: {
   requestConcurrency: 1,
},
```

i get 7 30sec timeout errors (office), but the total build process takes 1min 42secs... and I would have thought with a requestConcurrency of 1 that i should have at least a 2min 10sec delay in the process? (and just incase requestConcurrency is actually extra threads on top of the main, i thought about changing its value to 0 and it's still doing the same thing)

i've moved my local working wordpress install onto my server (as cms2.me.com) and its still throwing the same errors.

I'm thinking my setup is just trying to power through and is ignoring the concurrency settings and choking... will work out how to share my repo with @TylerBarnes

**Comment by adrianhewitt** [comment]
Invited @TylerBarnes :) it's the v2 branch i'm having issues with. and its super rough, but its hard to work on it with the media download issues

**Comment by adrianhewitt** [comment]
Just got the time to pair the project back to just the queries and made it public

https://github.com/adrianhewitt/adrianhewitt.com-troubleshooting

**Comment by Piligrimas** [comment]
I really hoped that the stable version will fix this one, but sadly same problems happening with the new gatsby-source-wordpress plugin. While there aren't many media files everything works fine, but when I upload more media it starts showing this error... For more than 2 months I have a separate sandbox source with fewer media, so I could develop my project...

**Comment by TylerBarnes** [comment]
Recently a newer contributor split out request concurrency into 2 options, one for files and one for data requests. I think a mistake was made where file requests are still partially relying on the `GATSBY_CONCURRENT_DOWNLOAD` env var. @Piligrimas would you mind trying to lower that env var to see if it helps?
